theme: jekyll-theme-hacker
title: Welcome to HErC @ Hatch's homepage!
description: As part of the Hatch Certificate Lv. 3 Requirements, this webpage is being built so students can check some of the coach's work ;)
